syntax = "proto3";

package airline.aircraft;

import "common.proto";
 

// Aircraft Service
service AircraftService {
  rpc GetAllAircrafts(GetAllAircraftsRequest) returns (PaginatedAircraftList);
  rpc GetAircraftByCode(AircraftByCodeRequest) returns (Aircraft);
}

message GetAllAircraftsRequest {
  airline.common.PaginationRequest pagination = 1;
}

message AircraftByCodeRequest {
  string aircraft_code = 1;
}

message Aircraft {
  string aircraft_code = 1;
  string model = 2;
  int32 range = 3;
}

message AircraftList {
  repeated Aircraft aircrafts = 1;
}

message PaginatedAircraftList {
  repeated Aircraft aircrafts = 1;
  airline.common.PageInfo page_info = 2;
}