syntax = "proto3";

package airline.airport;

 import "common.proto";
 

// Airport Service
service AirportService {
  rpc GetAllAirports(GetAllAirportsRequest) returns (PaginatedAirportList);
  rpc GetAirportByCode(AirportByCodeRequest) returns (Airport);
}

message GetAllAirportsRequest {
  airline.common.PaginationRequest pagination = 1;
}

message AirportByCodeRequest {
  string airport_code = 1;
}

message Airport {
  string airport_code = 1;
  string airport_name = 2;
  string city = 3;
  string timezone = 4;
}

message AirportList {
  repeated Airport airports = 1;
}

message PaginatedAirportList {
  repeated Airport airports = 1;
  airline.common.PageInfo page_info = 2;
}