syntax = "proto3";

package airline.booking;

 import "common.proto";
 

// Booking Service
service BookingService {
  rpc GetAllBookings(GetAllBookingsRequest) returns (PaginatedBookingList);
  rpc GetBookingByRef(BookingByRefRequest) returns (Booking);
  rpc StreamBookingCreated(airline.common.Empty) returns (stream BookingEvent);
  rpc StreamBookingUpdated(airline.common.Empty) returns (stream BookingEvent);
  rpc StreamBookingCanceled(airline.common.Empty) returns (stream BookingEvent);
}

message GetAllBookingsRequest {
  airline.common.PaginationRequest pagination = 1;
}

message BookingByRefRequest {
  string book_ref = 1;
}

message Booking {
  string book_ref = 1;
  string book_date = 2;
  float total_amount = 3;
}

message BookingList {
  repeated Booking bookings = 1;
}

message PaginatedBookingList {
  repeated Booking bookings = 1;
  airline.common.PageInfo page_info = 2;
}

message BookingEvent {
  Booking booking = 1;
}