syntax = "proto3";

package airline.ticket;

 import "common.proto";
 

// Ticket Service
service TicketService {
  rpc GetAllTickets(GetAllTicketsRequest) returns (PaginatedTicketList);
  rpc GetTicketByNo(TicketByNoRequest) returns (Ticket);
}

message GetAllTicketsRequest {
  airline.common.PaginationRequest pagination = 1;
}

message TicketByNoRequest {
  string ticket_no = 1;
}

message Ticket {
  string ticket_no = 1;
  string book_ref = 2;
  string passenger_id = 3;
  string passenger_name = 4;
  string contact_data = 5;
}

message TicketList {
  repeated Ticket tickets = 1;
}

message PaginatedTicketList {
  repeated Ticket tickets = 1;
  airline.common.PageInfo page_info = 2;
}