syntax = "proto3";

package airline.ticketflight;

 import "common.proto";
 

// TicketFlight Service
service TicketFlightService {
  rpc GetAllTicketFlights(GetAllTicketFlightsRequest) returns (PaginatedTicketFlightList);
  rpc GetTicketFlightByTicketAndFlightId(TicketFlightByTicketAndFlightIdRequest) returns (TicketFlight);
}

message GetAllTicketFlightsRequest {
  airline.common.PaginationRequest pagination = 1;
}

message TicketFlightByTicketAndFlightIdRequest {
  string ticket_no = 1;
  int32 flight_id = 2;
}

message TicketFlight {
  string ticket_no = 1;
  int32 flight_id = 2;
  string fare_conditions = 3;
  float amount = 4;
}

message TicketFlightList {
  repeated TicketFlight ticket_flights = 1;
}

message PaginatedTicketFlightList {
  repeated TicketFlight ticket_flights = 1;
  airline.common.PageInfo page_info = 2;
}